### ISSUE TITLE
incorporate model_1b and model_2c results into aggregate risk score

### ISSUE THREAD

**Issue by brooksandrew** [home-fire-risk/smoke_alarm_models#20]
Incorporate results from these models into aggregate_risk/aggregate_models.R

dependency on #18 and #13

**Comment by brooksandrew** [comment]
completed by @brooksandrew with ffa482212a01dfadc8305f23cebb64258edfde82 still need to update with model once model_2c is complete

**Comment by margaretmf** [comment]
Hi Andrew,

Because there is so much data, which would be difficult to request from the
API in R, I worked on using qgis with the attached data (and this census
tact file https://www.gisnuts.com/terra/CensusData) to count the number
of points in each polygon. I'm experiencing some issues with that. I may
try a few other things this evening, but if anyone else can try working on
this that would be great.

Sorry for the delay.

Margaret

_Margaret Furr_
_University of Virginia Graduate_
_MS in Data Science, '15_
_BA in History, '14_
